### PR TITLE
Refactor/flutter updates

### LINKED ISSUE #6: install_android_gradle command name is misleading
## Orb version:
1.0.0

## What happened:

install_android_gradle seems like it should install Android Gradle but it runs:

gradle androidDependencies

## Expected behavior:

the name should maybe say install_gradle_android_dependencies

### LINKED ISSUE #8: CircleCI flutter orb unexpected argument: version
## Orb version:
1.0.1

## What happened:
I've got the error:
```
Error calling workflow: 'distribute'Error calling job: 'distribute'Error calling command: 'flutter/install_sdk_and_pub'Unexpected argument(s): version
```

## Expected behavior:
It should download and install Flutter version passed as argument version.

## Additional Information:
Yaml file:

```
version: '2.1'
orbs:
  flutter: circleci/flutter@1.0.1
jobs:
  distribute:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 2.8.1
          app-dir: ./app
      - flutter/install_ios_pod:
          app-dir: ./app
      - flutter/install_ios_gem:
          app-dir: ./app
      - run:
          command: bundle exec fastlane ios distribute
          working_directory: ios
workflows:
  distribute:
    jobs:
      - distribute
```

### LINKED ISSUE #13: CircleCI outdated usage examples
If someone tries to copy the exact usage examples, builds will fail. For example, not adding the `checkout` step will result in a vague error related to the caching mechanism not being able to check the `pubspec.yaml` of the project file.

### LINKED ISSUE #14: Set default Flutter SDK to Flutter 3 stable
## Describe Request:
Set the default SDK to Flutter 3.0 stable

## Supporting Documentation Links:
https://docs.flutter.dev/development/tools/sdk/releases?tab=macos

### PR DESCRIPTION
**Pull request by JalexChen**
- Builds off #15 since it was a really old PR. Thank you @joshuadeguzman
- Closes #13 Updated examples and adds `- checkout` step so users who copy it verbatim are not confused
- Closes #14

This will be a patch release

### CODE REVIEW

**Comment by JalexChen** [comment]
@KyleTryon @ryanbourdais

**Review by felicianotech — CHANGES_REQUESTED** [review]
These changes shouldn't all be in one PR.

1. That's our recommended approach on the team.
2. You're forcing all users of the current major version to update just to get a bug fix (version param).

**Comment by JalexChen** [comment]
> These changes shouldn't all be in one PR.
> 
> 1. That's our recommended approach on the team.
> 2. You're forcing all users of the current major version to update just to get a bug fix (version param).

normally i would agree with the smaller PRs, but some of these updates were intertwined with the flutter version, dependency updates, and updating flutter would require some changes in the sample app

i would say the first three commits + checkout commit could be a patch version

the command name change and version parameter can be a minor change. in my mind they are technically "breaking" changes but not necessarily in how it works, so i think this makes more sense. i'd like to bundle these two together to limit incrementing the version

how does that sound?

@felicianotech

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:1fcffd3ba8b7aeb448319c7a6261b092f30eeee0

**Comment by JalexChen** [comment]
@ryanbourdais - the version changes were already included in #15, but i updated them to something more recent since they are almost a year of updates

i've updated the PR to only include those changes and will have a separate PRs for the breaking changes

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:e6dce8719ff56ec3d4814893c18dfecdab03faf9

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:683c2ae2707f44f91e3eb76175df953626dd9a54

**Review by felicianotech — APPROVED** [review]
If we're not doing a major change, I guess that's fine, but I wouldn't do patch either. So at least a minor bump.

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:b6d07fa74698c0bf289f5c991c71b48f5d898a89

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:e6dce8719ff56ec3d4814893c18dfecdab03faf9

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=1.2.0

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:b6d07fa74698c0bf289f5c991c71b48f5d898a89

**Pull request merged**
