### PR TITLE
fix: fixed xcode sdk install

### LINKED ISSUE #27: Install SDK broken on XCode 14.2.0 executor
## Orb version:

2.0.0

## TLDR; 

This should be the only thing that needs to change [here](https://github.com/CircleCI-Public/flutter-orb/blob/main/src/scripts/install-sdk.sh#L21):

```diff
- echo "export PATH=$INSTALL_LOCATION/flutter/bin:$PATH" >> "$BASH_ENV"
+ echo "export PATH=$INSTALL_LOCATION/flutter/bin:\$PATH" >> "$BASH_ENV"
```

## What happened:

I think I discovered a bug, but also have a possible quick solution. Although the `flutter/install_sdk` command appears to succeed, there is some flakiness in the install and some errors in `doctor`. This manifests itself with an error any time ruby is invoked. Some examples:

Running `flutter doctor`:
image

Running `rbenv version`
image

From there, cocoapods and anything gem related breaks down in all kinds of ways, but I think it will be more helpful to show the cause and solution than to exhaust all the side effect errors that occur. 

## Additional Information:

The easiest way to replicate this is with the following config file. 

<details>
  <summary>config.yml</summary>

```yml
version: 2.1

jobs:
  basic-install:
    macos:
      xcode: 14.2.0
    steps:
      - run: rbenv version
      - flutter/install_sdk
      - run: rbenv version
  minimal-broken:
    macos:
      xcode: 14.2.0
    steps:
      - run:
          name: '$PATH variable not escaped'
          command: |
            rbenv version
            echo "export PATH=/Users/distiller/development/flutter/bin:$PATH" >> "$BASH_ENV"
            rbenv version
  minimal-working:
    macos:
      xcode: 14.2.0
    steps:
      - run:
          name: 'Escaped \$PATH variable'
          command: |
            rbenv version
            echo "export PATH=/Users/distiller/development/flutter/bin:\$PATH" >> "$BASH_ENV"
            rbenv version
orbs:
  flutter: circleci/flutter@2.0.0

workflows:
  bug-report:
    jobs:
      - basic-install
      - minimal-broken
      - minimal-working
```
</details>

image

In here, the job `basic-install` is an integrated example which uses the orb and shows how the install breaks the bash command: `rbenv version`. The two jobs `minimal-working` and `minimal-broken` show where the root cause of this might be occurring. I suspect that ruby is doing something with the `PATH` variable, and the flutter sdk is overwriting this variable, rather than constructing it in `$BASH_ENV`.

### Basic Install

Using the following steps, the first `rbenv version` succeeds but the second call fails just after installing:

```yml
steps:
  - run: rbenv version
  - flutter/install_sdk
  - run: rbenv version
```

image

### Broken

`minimal-broken`, performing the PATH overwrite with [current code](https://github.com/CircleCI-Public/flutter-orb/blob/fa0ac2b381b5eb275fe5279ad7b2ae2de380b058/src/scripts/install-sdk.sh#L21).

```yml
command: |
  rbenv version
  echo "export PATH=/Users/distiller/development/flutter/bin:$PATH" >> "$BASH_ENV"
  rbenv version
```

image

### Working

vs `minimal-working`, which adds an escaped character next to the $ sign in `$PATH`

```yml
command: |
  rbenv version
  echo "export PATH=/Users/distiller/development/flutter/bin:\$PATH" >> "$BASH_ENV"
  rbenv version
```

image

## Expected behavior:

`rbenv version` should not exit with an error after installing flutter sdk on xcode 14.2 executor.

### PR DESCRIPTION
**Pull request by ryanbourdais**
This PR should close #27, also adds an extra test command to both integration tests.

### CODE REVIEW

**Review by JalexChen — COMMENTED** [review]
~~should these tests incorporate a build fail if the version doesn't exist or does not match?~~ nevermind i read it wrong

**Review by JalexChen — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:ef9c73fae2397a5041274dc261c0d040d97210ca

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:c5d0c4f1be9e1bb0a1d52e52bce502cc84e869a6

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:c5d0c4f1be9e1bb0a1d52e52bce502cc84e869a6

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=2.0.1

**Pull request merged**
