### PR TITLE
Fix/resolved conflict edit

### PR DESCRIPTION
**Pull request by JalexChen**
- a resolved conflict reverted a change in the examples provided. this fixes that
- since this will also be the last PR for the major release due to breaking changes, the examples were updated to reflect the version the examples will be using
- examples show both the major.minor and major.minor.patch versions available to users

### CODE REVIEW

**Review by ryanbourdais — APPROVED** [review]
LGTM

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:fa0ac2b381b5eb275fe5279ad7b2ae2de380b058

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:fa0ac2b381b5eb275fe5279ad7b2ae2de380b058

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=2.0.0

**Pull request merged**
