### PR TITLE
Add the ability to install from the beta releases channel

### PR DESCRIPTION
**Pull request by marboledacci**
This is a copy of #48

### CODE REVIEW

**Review by david-montano-circleci — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:e866e5d6abc9a6267785ed244e17a91099e4b510

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:7d9e1a2b49f752ef194333fc0561b056591bcf3c

**Comment by LegendAF** [comment]
Thank you for seeing this through!

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:7d9e1a2b49f752ef194333fc0561b056591bcf3c

**Comment by LegendAF** [comment]
Any idea when this will be published @marboledacci? Should I just use the dev orb?

**Comment by marboledacci** [comment]
This was already release, it is on version 2.1

**Comment by LegendAF** [comment]
@marboledacci The dev orb expired. I don't see the updated code being deployed what version should I be using?
https://circleci.com/developer/orbs/orb/circleci/flutter

Nothing here?
https://circleci.com/developer/orbs/orb/circleci/flutter?version=2.1

**Comment by marboledacci** [comment]
Hello @LegendAF sorry for that, there had been a problem doing that release and we hadn't realized, it is solved now and the version is published.

**Pull request merged**
